class Adhoc:
    def __init__(self, verbose=False):
        self.verbose = verbose

    def abbrev_tbl(self):
        tmp_dt = {
            "Houston Texans": "htx",
            "Cleveland Browns": "cle",
            "Jacksonville Jaguars": "jax",
            "Carolina Panthers": "car",
            "Buffalo Bills": "buf",
            "htx": "Houston Texans",
            "cle": "Cleveland Browns",
            "jax": "Jacksonville Jaguars",
            "car": "Carolina Panthers",
            "buf": "Buffalo Bills",
            "oti": "Tennessee Titans",
            "Tennessee Titans": "oti",
            "cin": "Cincinnati Bengals",
            "Cincinnati Bengals": "cin",
            "ram": "Los Angeles Rams",
            "Los Angeles Rams": "ram",
            "rai": "Las Vegas Raiders",
            "Las Vegas Raiders": "rai",
            "sdg": "San Diego Chargers",
            "San Diego Chargers": "sdg",
            "was": "Washington Football Team",
            "Washington Football Team": "was",
            "nwe": "New England Patriots",
            "New England Patriots": "nwe",
            "nyg": "New York Giants",
            "New York Giants": "nyg",
            "nyj": "New York Jets",
            "New York Jets": "nyj",
            "nor": "New Orleans Saints",
            "New Orleans Saints": "nor",
            "phi": "Philadelphia Eagles",
            "Philadelphia Eagles": "phi",
            "crd": "Arizona Cardinals",
            "Arizona Cardinals": "crd",
            "rav": "Baltimore Ravens",
            "Baltimore Ravens": "rav",
            "kan": "Kansas City Chiefs",
            "Kansas City Chiefs": "kan",
            "clt": "Indianapolis Colts",
            "Indianapolis Colts": "clt",
            "gnb": "Green Bay Packers",
            "Green Bay Packers": "gnb",
            "dal": "Dallas Cowboys",
            "Dallas Cowboys": "dal",
            "sfo": "San Francisco 49ers",
            "San Francisco 49ers": "sfo",
            "atl": "Atlanta Falcons",
            "Atlanta Falcons": "atl",
            "mia": "Miami Dolphins",
            "min": "Minnesota Vikings",
            "chi": "Chicago Bears",
            "det": "Detroit Lions",
            "tam": "Tampa Bay Buccaneers",
            "sea": "Seattle Seahawks",
            "den": "Denver Broncos",
            "pit": "Pittsburgh Steelers",
        }

        return tmp_dt
